### ISSUE TITLE
领域模型问题

### ISSUE THREAD

**Issue by lijm48** [earn-big-money/Dashboard#1]
主要有以下问题：
（1）为什么领域模型图里有两个一样的主页，主页这个我觉得完全没有用。。。
（2）发布人是否只能发布一个任务，个人认为应该是1对*
（3）任务是否最多只有一个用户，不是的话应该是1对*
（4）发布人是否属于用户，是否需要使用继承箭头？
（5）线画得有点乱，用例图也是
以上内容仅供参考，未必正确，不知道领域模型图是否有别的模块，感觉有点少？

**Comment by ZTao-z** [comment]
感谢建议，我们会参考你的意见进行改进
